# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39375a4def667a729e8fd7ce40fbc35b3704e0f33db2aed3e5aa30e641753506528366b5a7b86154b60c9193e2ebc2603630acdeade06a82e38b360b21681a0a

test:
  secret_key_base: 563e7e99aa5192b6a68d85b8e4df82936ab3dee51aa69f4f5eac2ecc42b871dc3962d48c73ee5efe9cb2e40c1e3ee8f135e04fee88effc730fe64ac3fa1cc44c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
